### ISSUE TITLE
Implement the component related functions taking into account the state management

### ISSUE THREAD

**Issue by CosminNechifor** [CosminNechifor/IKHNAIE#12]
Parent issue: #11 

## State management

The **state** field is gonna be one of the must important fields of a component, because it allows and restricts which actors have access to the components.

![state_machine](https://user-images.githubusercontent.com/22676160/55027844-eac42c80-500e-11e9-9250-99956d5e1892.png)

## Functions that have to be implemented:

- [x] updateComponentName
- [x] updateComponentExpiration
- [x] updateComponentPrice
- [x] updateOtherInformation
- [x] addToOtherComponent
- [x] removeComponentFromOtherComponent
- [x] flagAsBroken (explained in: https://github.com/CosminNechifor/IKHNAIE/issues/14#issuecomment-483783517)
- [x] flagAsExpired (explained in: https://github.com/CosminNechifor/IKHNAIE/issues/14#issuecomment-483847953)
- [x] repair (explained here: https://github.com/CosminNechifor/IKHNAIE/issues/14#issuecomment-483783517)

## Events the ``ComponentContract`` will emit while performing the functions:
------
- **ComponentCreated** &rarr; emitted when we create a component
- **ComponentUpdated** &rarr; emitted when we change the value of one field. Musty when the methods above are being called.
- **ComponentSubmitedForSale** &rarr; emitted when a component is submitted for sale.
- **ComponentWasBought** &rarr; emitted when someone else bought the component (**This is market related so it wont be added to the ``Component`` contract**)
- **ComponentRemovedFromMarket** &rarr; emitted when a component was removed by the owner from the market (**Market related so it wont be added to the ``Component`` contract**)
- **OwnershipTransferred**  &rarr; emitted when a component is bought.

**Comment by CosminNechifor** [comment]
FSM has to be improved.

**Comment by CosminNechifor** [comment]
![new_state_machine](https://user-images.githubusercontent.com/22676160/55069697-5351ee80-508d-11e9-8217-05f08de70d93.png)

Exp &rarr; NR (NeedsRecycled)

**Comment by CosminNechifor** [comment]
Not closing this till #14 gets solved

**Comment by CosminNechifor** [comment]
Fixed by: #41
